name: Issue Template
description: ''
title: ''
labels: ''
assignees: ''

body:
  - type: textarea
    id: issue_description
    attributes:
      label: ''
      placeholder: 'Describe the issue/problem. Describe proposed solution, and at least one next step to get started'
    validations:
      required: true
