name: Issue Template
description: 'issue template'
title: 'Issue Title Here'
body:
  - type: textarea
    id: issue_description
    attributes:
      label: 'Issue Details'
      placeholder: 'Describe the issue/problem. Describe proposed solution, and at least one next step to get started.'
    validations:
      required: true
